version: '2'
services:

    # FridgeBuffet Application

    app:
        build:
        context: ./
        dockerfile: app.dockerfile
        working_dir: /var/www
        volumes:
            - ./:/var/www
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=database"

    # NGINX Web Server

    web:
        build:
        context: ./
        dockerfile: web.dockerfile
        working_dir: /var/www
        volumes_from:
            - app
        ports:
            - "8080:80"

    # MySQL Database Server
    # Change to MariaDB

    database:
        image: mysql:5.6
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            - "MYSQL_DATABASE=fridgebuffet"
            - "MYSQL_USER=root"
            - "MYSQL_PASSWORD=root"
            - "MYSQL_ROOT_PASSWORD=root"
        ports:
            - "33061:3306"

    volumes:
        dbdata:
